name: Update version and create Release's PR workflow

on:
  workflow_dispatch: 
    inputs:
      version:
        description: "Version Name"
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn install
      - name: Set up Git
        run: |
          git config --global user.name noreply@github.com
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
      - name: Pull Main & Update Version
        id: update_version
        run: |
          git fetch
          git merge origin/main --no-verify --no-edit
          yarn version --${{ github.event.inputs.version }} --no-git-tag-version
          echo "version=v$(npm pkg get version | tr -d '\"')" >> $GITHUB_OUTPUT
      - name: Update Changelog
        id: update_changelog
        run: |
          sed -i 's/Unreleased/${{ steps.update_version.outputs.version }}/g'   CHANGELOG.md
      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GENERAL_ACCESS_TOKEN }}
          branch: release/${{ steps.update_version.outputs.version }}
          title: "Release: ${{ steps.update_version.outputs.version }} Pull Request"
          body: "This pull request contains the updated package.json with the new release version"
          base: master